# Generated by Django 5.2.1 on 2025-05-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_about_description_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person giving the testimonial.', max_length=100)),
                ('role', models.CharField(blank=True, help_text='Their role or title (e.g., CEO, Angel Investor).', max_length=100)),
                ('company', models.CharField(blank=True, help_text='Their company or organization (optional).', max_length=100)),
                ('text', models.TextField(help_text='The testimonial text (what the user says about FoundrFuse).')),
                ('user_type', models.CharField(choices=[('founder', 'Founder'), ('investor', 'Investor')], help_text='Is this testimonial from a Founder or an Investor?', max_length=10)),
                ('category', models.CharField(blank=True, help_text='Industry or category (e.g., Tech, Healthcare).', max_length=100)),
                ('date', models.DateField(help_text='Date when the testimonial was given.')),
                ('avatar', models.ImageField(blank=True, help_text='Optional: Upload a profile photo for this testimonial.', null=True, upload_to='testimonials/')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-date'],
            },
        ),
    ]
