# Generated by Django 5.2.1 on 2025-05-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='FAQ question for the Feature page.', max_length=255)),
                ('answer', models.TextField(help_text='Answer to the FAQ question.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance on the Feature page.')),
            ],
            options={
                'verbose_name': 'Feature Page FAQ',
                'verbose_name_plural': 'Feature Page FAQs',
                'ordering': ['order'],
            },
        ),
    ]
