# Generated by Django 5.2.1 on 2025-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_featurefaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='FAQ question for the Founders page.', max_length=255)),
                ('answer', models.TextField(help_text='Answer to the FAQ question.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance on the Founders page.')),
            ],
            options={
                'verbose_name': 'Founder Page FAQ',
                'verbose_name_plural': 'Founder Page FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FounderSuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the founder.', max_length=100)),
                ('role', models.CharField(blank=True, help_text='Role or title (e.g., Founder & CEO).', max_length=100)),
                ('company', models.CharField(blank=True, help_text='Company or startup name.', max_length=100)),
                ('quote', models.TextField(help_text='Success story or testimonial quote.')),
                ('avatar', models.ImageField(blank=True, help_text='Photo of the founder.', null=True, upload_to='success_stories/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order.')),
            ],
            options={
                'verbose_name': 'Founder Success Story',
                'verbose_name_plural': 'Founder Success Stories',
                'ordering': ['order'],
            },
        ),
    ]
