# Generated by Django 5.2.1 on 2025-05-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='razorpay', max_length=20),
        ),
    ]
